name: 'Releases'
description: 'Create realise to for projects'
author: 'Bennett Benedict'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  FILE_LOCATION:
    description: 'Upload File Location'
    required: true

runs:
  using: 'node12'
  main: 'action/index.js'
