name: 👷

on:
  pull_request:
    types: [opened]
  push:
    branches: [main]

jobs:
  build:
    # if: ${{ github.event.label.name == 'release' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.ACTION_GITHUB_TOKEN}}
          ASSET_NAME: ${{secrets.ASSET_NAME}}
          FILE_LOCATION: ${{secrets.FILE_LOCATION}}
          ASSET_TYPE: ${{secrets.ASSET_TYPE}}
