name: 👷

on:
  pull_request:
    types: [opened]

jobs:
  build:
    if: ${{ github.event.label.name == 'release' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.ACTION_GITHUB_TOKEN}}
